### ISSUE TITLE
Jason Blanchard isn't proven to have a cameo in this year's HHC yet

### ISSUE THREAD

**Issue by jeffmcjunkin** [CounterHack/HolidayHack2020#1]
Title says it all. I think it's pretty clear that it's a bug, unless there's more to see ;)

**Comment by iagox86** [comment]
Can't reproduce.

**Comment by tkh16** [comment]
@jeffmcjunkin Try harder!

**Comment by edskoudis** [comment]
Ha! True. So, does Jeff get to see these replies?

**Comment by jeffmcjunkin** [comment]
He does! As does the rest of the internet!

Hello, internet!

**Comment by edskoudis** [comment]
YAY!

**Comment by jeffmcjunkin** [comment]
I accept this evidence and will move on with life: https://twitter.com/tootsierollpop8/status/1336824846395838465?s=19

**Comment by crahan** [comment]
Since I saw Jason at HHC this year, I agree with the final assessment of this issue :D
