### ISSUE TITLE
linux primer defect

### ISSUE THREAD

**Issue by arg0user** [CounterHack/HolidayHack2020#10]
The question about finding a file of a certain size in /opt/munchkin_den takes a solution that only finds file greater than 108k.  The solution should require > 108K and < 110K

...or maybe it was designed otherwise....

**Comment by chrisjd20** [comment]
What command are you using?

**Comment by chrisjd20** [comment]
Oh Ok I see what your saying. Id have to test it again to verify but I think thats fine if so... The learning objective is to learn the `-size` flag and either instance, thats accomplished. Thanks for the feedback. Something to look into for the future for sure.

**Comment by arg0user** [comment]
cool, yah...quesion seemed to imply you needed both upper and lower limits...but learning / understanding of -s**e was there...thx chris

**Comment by chrisjd20** [comment]
Well that WAS the intent but the learning objective is still there. We will probably go back and refine it ( thanks to your feedback ) but yea no critical changes needed.

**Comment by tkh16** [comment]
Thanks again for your feedback, @arg0user!
