### ISSUE TITLE
S3 bucket not working in-game

### ISSUE THREAD

**Issue by Shadylbx** [CounterHack/HolidayHack2020#15]
previously modified the wordlist with the name of the bucket, all lower and it was working for me.  The in Game can no longer find bucket, but I can access it directly from local browser.

**Comment by Shadylbx** [comment]
![bucket no found](https://user-images.githubusercontent.com/8661655/102021302-ed1f6a80-3d4c-11eb-8db7-db56a2f0a366.jpg)

**Comment by tkh16** [comment]
Closing this as a duplicate of #16.  Thanks for the report; we're looking into the issue.
