### ISSUE TITLE
Some users are reporting kiosk wrapper3000 not found

### ISSUE THREAD

**Issue by john-r2** [CounterHack/HolidayHack2020#16]
![image](https://user-images.githubusercontent.com/34966634/102021347-34a5f680-3d4d-11eb-8956-26f7a9e9443a.png)

**Comment by joswr1ght** [comment]
Interesting, I'm not sure what would cause this. It appears to be working OK for me, tested just now from my Mac and from in-game.

<img width="1792" alt="Screen Shot 2020-12-13 at 2 25 44 PM" src="https://user-images.githubusercontent.com/1318817/102021688-7c2d8200-3d4f-11eb-882c-50de607a9b62.png">

Do you get an error when you run `curl http://s3.amazonaws.com/wrapper3000/package`

**Comment by john-r2** [comment]
It works for me too.  There were two users in the objective-2 chat that said they had the problem.  One said it starting working when he changed browsers.

This is a duplicate with ticket 15--ShadyLBX was the one who reported it to me

**Comment by tkh16** [comment]
Also works for me.  We do load balance the terminal instances, so it's conceivably possible that certain servers are having  the problem and others aren't.  Hmm...

**Comment by tkh16** [comment]
I'm wondering if outbound Internet access isn't working on affected instances, and this is how it manifests itself...

**Comment by joswr1ght** [comment]
Closing this to follow activity on #23
