### ISSUE TITLE
Unable to Sign In

### ISSUE THREAD

**Issue by jh1-git** [CounterHack/HolidayHack2020#18]
I get to the sign-in page, enter my username and password, and the spinning dot starts and spins forever, I tried with both Firefox and Chrome and got the same results.

![image](https://user-images.githubusercontent.com/1023383/102050309-351fab00-3da8-11eb-9a41-7bc14ce1869d.png)

**Comment by akat12** [comment]
+1 for this issue.  Chrome details:

Google Chrome | 87.0.4280.88 (Official Build) (64-bit) (cohort: Stable)
-- | --
Revision | 89e2380a3e36c3464b5dd1302349b1382549290d-refs/branch-heads/4280@{#1761}
OS | Windows 10 OS Version 1909 (Build 18363.1256)

**Comment by edskoudis** [comment]
Yes, indeed.  We apologize for the interruption.  The ops elves are working on restoring service.

Thank you again for your understanding.

—Ed.

**Comment by tkh16** [comment]
Our downtime from this morning has been resolved, and we believe that we have resolved the underlying issue.  Marking this as closed unless the same issue comes up again.  Thanks again for your reports and for your patience!
