### ISSUE TITLE
Dialog from Jingle Ringford 

### ISSUE THREAD

**Issue by SWaters-3000** [CounterHack/HolidayHack2020#32]
Would be great, and maybe these is one, but dialogs disappear quickly. As I'm looking around about 1 dialogue, I have just missed the next one...  Is there a way to save the dialog message to review again without having to keep Click Jacking Mr. Ringford? :-)
Also, I keep getting logged out of the challenge every time I switch tabs in the browser to go ready information about the challenge on a different HC2020 site...?  How can I just stay logged in?

Also, please add to the drawing too...   thanks guys!

**Comment by treefort** [comment]
Hey! You can select and view previous NPC conversations via this drop-down menu:
![Screenshot_20201220-094211](https://user-images.githubusercontent.com/1132492/102716131-d70f2e00-42a7-11eb-896c-a4615af4b421.png)

**Comment by treefort** [comment]
I'm not sure why you would lose your session every time you switch tabs. That definitely shouldn't happen. Try an F5/shift+F5/ctrl+shift+F5 next time it happens and see if you get back in.

**Comment by treefort** [comment]
One last thing: you can only have HHC open in one tab, so if you have open the whole game in a new tab, your old tab will be logged out.

**Comment by SWaters-3000** [comment]
The issue of loosing the session isn't happening anymore.  But, I didn't have the same HHC open in more than 1 tab at the time.  But, issue appeared to resolve itself now...  thank you! :-)
