### ISSUE TITLE
Objective 10 (Santavator Fingerprint Scanner) did not give credit   [Spoiler]

### ISSUE THREAD

**Issue by cameronkerrnz** [CounterHack/HolidayHack2020#36]
I have completed the challenge to bypass the fingerprint scanner in the santavator. There were a few attempts.

I finally worked it out using the following Javascript in the console to reload the iframe with a slightly different src attribute, adding in the yellowlight. I was already in the guise of Santa, so I didn't need to do anything with besanta. The src I had copied from the existing src attribute.

`document.getElementsByTagName("iframe")[0].src="https://elevator.kringlecastle.com?challenge=santamode-elevator3&id=88f0967f-c42f-4534-938a-c426655b7c03&username=pungpungpanda&area=santamode-santavator3&location=1,2&tokens=marble,nut2,candycane,ball,elevator-key,greenlight,redlight,yellowlight,workshop-button,besanta"
`

Or more generally (as I need to do this every time I want to use the elevator to get to Santa's Office:

`
document.getElementsByTagName("iframe")[0].src = document.getElementsByTagName("iframe")[0].src.replace("greenlight,redlight", "greenlight,redlight,yellowlight")
`

I had previously been attempting this within the iframe itself (not realising the iframe was now the top of the document), and had therefore obtained and positioned the yellow light. I just needed to futz with the iframe src.

This allowed my to activate the button for Santa's Office and click on the fingerprint scanner.

Here's a screenshot of what I see currently in the (latest version) of Chrome Dev Tools

![image](https://user-images.githubusercontent.com/938702/103457485-aa0d5180-4d64-11eb-9cf3-ad32a7795a4e.png)

And while I have been into Santa's Office and spoken with Tinsel Upatree and downloaded the Blockchain data for the next objective, I don't get the objective showing as complete in my badge.

![image](https://user-images.githubusercontent.com/938702/103457508-e17bfe00-4d64-11eb-9a6e-f2ff8b0ff593.png)

I'm no Javascript/Web developer, but this seems like a reasonable way to solve this challenge.

Thanks for creating HHC; its great to stretch the skills.

**Comment by treefort** [comment]
The only way we can know for sure that you've bypassed the fingerprint scanner is if you do it as a regular player. 🙂

**Comment by cameronkerrnz** [comment]
Thanks, I got to wondering if that might be the case.
