### ISSUE TITLE
Linux Primer Issue

### ISSUE THREAD

**Issue by santaisme** [CounterHack/HolidayHack2020#37]
When I accidentally write something incorrectly (which is often because I'm new to coding) then I get stuck in a blank loop and can't go further so I then close it and have to restart. It is also very easy to accidentally leave and loose all your progress.
![image](https://user-images.githubusercontent.com/78025278/105843789-d8d3bc00-5fe0-11eb-96ee-5f9248e1752c.png)

**Comment by chriselgee** [comment]
Thanks for filing the issue!  With _most_ traps like this, you can hit <Ctrl>c to break out.  In that specific case with `cat`, you can also send an "End of File" character with <Ctrl>d.  That's known/expected functionality with Linux.

As to losing progress, yes, that's something we may address at some point.  It's tricky to maintain that progress though, especially when some people _want_ to start back over from the beginning.  But, again, thanks for the input!  We're always looking to make our challenges better.

-Chris
-Holiday Hack Team
