### ISSUE TITLE
elfcode: elf.ask_munch(0) brings back undefined on level 7

### ISSUE THREAD

**Issue by DigitalSkateboarder** [CounterHack/HolidayHack2020#8]
As the subject says, elf.ask_munch(0) brings back undefined on level 7

**Comment by chrisjd20** [comment]
the elf.ask_munch is never called for on Level 7. Read the task more closely. He's asking you to simply submit a function that performs the task and returning the value its looking for.
For example:


```javascript
// elf.ask_munch(0) is never used
elf.tell_munch(function(MUNCHSPASSEDOBJECT) {
 // DO WHATEVER THE MUNCHKIN IS ASKING YOU TO DO
 // to MUNCHSPASSEDOBJECT
 return SOMEVALUEFROMMUNCHSPASSEDOBJECT
})
```

**Comment by chrisjd20** [comment]
You could also abstract the function out  and simply pass the function name. That should be whats in the example when you click on the munchkin for levels 7 and 8.

```javascript
function ParseMunchData(MUNCH_PASSED_OBJ) {
 // do the required task to MUNCH_PASSED_OBJ
 return desired_value_from_MUNCH_PASSED_OBJ
}
// elf.ask_munch(0) is never used
elf.tell_munch(ParseMunchData)
```

**Comment by chrisjd20** [comment]
In fact, if you click on the munchkin in the **CURRENT LEVEL OBJECTS** window, you'll see a similar example:

![image](https://user-images.githubusercontent.com/11812223/101814014-88190a00-3aeb-11eb-9712-ad9b8f9fa120.png)

**Comment by DigitalSkateboarder** [comment]
Hey, really appreciate you getting back so quick! Thank you.

Must be missing something - I did exactly as mentioned but it wasn't working. Did something in jsFiddle passing through that example array of arrays and it worked.
